{"name": "test_InvalidPassword_ErrorMessageShown", "status": "passed", "description": "Login with valid username and invalid password and check that password error message is shown", "attachments": [{"name": "log", "source": "8ebc68d4-f5c4-4c77-8db1-0e19b5c3abb5-attachment.txt", "type": "text/plain"}], "start": 1745233822714, "stop": 1745233823848, "uuid": "9e06e979-d673-4c01-9681-1151bd418077", "historyId": "2d49b488a03f042b1f1d0c77c7867d50", "testCaseId": "2d49b488a03f042b1f1d0c77c7867d50", "fullName": "tests.test_login.TestLogin#test_InvalidPassword_ErrorMessageShown", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "18972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}