[32mINFO    [0m root:test_calculator.py:40 Starting test for valid addition operation with login.
[32mINFO    [0m root:test_calculator.py:48 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}
[32mINFO    [0m root:test_calculator.py:51 Login response status code: 200
[32mINFO    [0m root:test_calculator.py:54 Login response data: {'message': None, 'data': {'success': True, 'token': '3959a741-6913-4068-a017-b853be6d96e7'}, 'status': 'success'}
[32mINFO    [0m root:test_calculator.py:57 Token received: 3959a741-6913-4068-a017-b853be6d96e7
[32mINFO    [0m root:test_calculator.py:58 Starting test for valid addition operation.
[32mINFO    [0m root:test_calculator.py:66 Sending calculation request: {'op1': 5, 'operation': '+', 'op2': 3}
[32mINFO    [0m root:test_calculator.py:71 Received response with status code: 200
[32mINFO    [0m root:test_calculator.py:74 Calculation response data: {'message': None, 'data': 8, 'status': 'success'}
[32mINFO    [0m root:test_calculator.py:80 The result of the addition operation is correct.