{"name": "test_InvalidPassword_ErrorMessageShown", "status": "passed", "description": "Login with valid username and invalid password and check that password error message is shown", "attachments": [{"name": "log", "source": "519fa89d-17de-4439-8d9f-70a7d9f22520-attachment.txt", "type": "text/plain"}], "start": 1745248360112, "stop": 1745248360948, "uuid": "aab59f61-a074-47b7-8ee0-aeaa6cefc2c5", "historyId": "2d49b488a03f042b1f1d0c77c7867d50", "testCaseId": "2d49b488a03f042b1f1d0c77c7867d50", "fullName": "tests.test_login.TestLogin#test_InvalidPassword_ErrorMessageShown", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "26048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}