INFO     root:test_calculator.py:37 Starting test for valid addition operation with login.
INFO     root:test_calculator.py:44 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}
INFO     root:test_calculator.py:47 Login response status code: 200
INFO     root:test_calculator.py:50 Login response data: {'message': None, 'data': {'success': True, 'token': '25304e19-d0ba-45a6-8247-c9cb52cfed1c'}, 'status': 'success'}
INFO     root:test_calculator.py:53 Token received: 25304e19-d0ba-45a6-8247-c9cb52cfed1c
INFO     root:test_calculator.py:54 Starting test for valid addition operation.
INFO     root:test_calculator.py:62 Sending calculation request: {'op1': 5, 'operation': '+', 'op2': 3}
INFO     root:test_calculator.py:67 Received response with status code: 200
INFO     root:test_calculator.py:70 Calculation response data: {'message': None, 'data': 8, 'status': 'success'}
INFO     root:test_calculator.py:76 The result of the addition operation is correct.