{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "broken", "statusDetails": {"message": "AttributeError: 'WebElement' object has no attribute 'Enter'", "trace": "self = <test_calc.TestCalculate object at 0x000001DAEAC6EE40>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n        self.login_page.log_in('admin','123')\n        logging.info('trying to add up for positive numbers')\n>       self.calculator_page.calc_add('5','3')\n\ntest_calc.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\calculator_page.py:16: in calc_add\n    self.click_calc_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.calculator_page.CalculatorPage object at 0x000001DAEDAC2000>\n\n    def click_calc_button(self):\n        calc_button = self.driver.find_element(*CalculatorPageLocators.calc_button)\n>       calc_button.Enter()\nE       AttributeError: 'WebElement' object has no attribute 'Enter'\n\npages\\calculator_page.py:35: AttributeError"}, "attachments": [{"name": "log", "source": "eaba19f2-f417-4d67-8f6a-3881529c0b5c-attachment.txt", "type": "text/plain"}], "start": 1745348468178, "stop": 1745348468651, "uuid": "88990edc-c9e2-4f13-9c4f-c1960116c1f4", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "13152-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}