INFO     root:test_calculator.py:31 Starting test for valid addition operation with login.
INFO     root:test_calculator.py:38 Attempting to log in with credentials: {'userName': 'admin', 'password': '123'}
INFO     root:test_calculator.py:41 Login response status code: 200
INFO     root:test_calculator.py:44 Login response data: {'message': None, 'data': {'success': True, 'token': 'f975469f-73a9-432b-8118-26fe1ad94a2a'}, 'status': 'success'}
INFO     root:test_calculator.py:47 Token received: f975469f-73a9-432b-8118-26fe1ad94a2a
INFO     root:test_calculator.py:48 Starting test for valid addition operation.
INFO     root:test_calculator.py:56 Sending calculation request: {'op1': 5, 'operation': '+', 'op2': 3}
INFO     root:test_calculator.py:61 Received response with status code: 200
INFO     root:test_calculator.py:64 Calculation response data: {'message': None, 'data': 8, 'status': 'success'}
INFO     root:test_calculator.py:70 The result of the addition operation is correct.