{"uuid": "9fa0b72f-01b8-4ced-a4e1-9932d7643cb8", "children": ["c3573be8-1953-4bb3-b82a-0185b79319c7"], "befores": [{"name": "_xunit_setup_method_fixture_TestCalculate", "status": "broken", "statusDetails": {"message": "NameError: name 'os' is not defined. Did you forget to import 'os'\n", "trace": "  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\User\\anaconda3\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\User\\Documents\\kirpichenko_tatyana\\Lesson10\\calc-web\\tests\\test_calc.py\", line 22, in setup_method\n    if not os.path.exists(self.screenshot_dir):\n           ^^\n"}, "start": 1745338010413, "stop": 1745338010418}], "start": 1745338010413, "stop": 1745338010606}