{"name": "test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestCalculate' object has no attribute 'login_page'", "trace": "self = <test_calc.TestCalculate object at 0x000001A8E63D3080>\n\n    def test_additionPositiveNumbers_SuccessfulLoginAndValidResult(self):\n        logging.info('trying to log in as valid user')\n>       self.login_page.log_in('admin', '123')\nE       AttributeError: 'TestCalculate' object has no attribute 'login_page'\n\ntest_calc.py:40: AttributeError"}, "attachments": [{"name": "log", "source": "8566930f-e884-46ff-a83e-49e9faf1b647-attachment.txt", "type": "text/plain"}], "start": 1745337892538, "stop": 1745337892539, "uuid": "1820d49a-7182-4de4-9276-71acca23ad56", "historyId": "017c2c166afb58f0ef9ef9f053aa6151", "testCaseId": "017c2c166afb58f0ef9ef9f053aa6151", "fullName": "tests.test_calc.TestCalculate#test_additionPositiveNumbers_SuccessfulLoginAndValidResult", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculate"}, {"name": "host", "value": "User-PC"}, {"name": "thread", "value": "20888-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_calc"}]}